apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - bases/pgshard.io_pgshardcatalogactivations.yaml
  - bases/pgshard.io_pgshardclusters.yaml
  - bases/pgshard.io_pgshardrestores.yaml
