apiVersion: v1
kind: Secret
metadata:
  name: webhook-fencing-key
  namespace: system
  annotations:
    pgshard.io/pod-fencing-keyless-upgrade-request: v1
  labels:
    app.kubernetes.io/name: pgshard-operator
    app.kubernetes.io/component: admission
    app.kubernetes.io/managed-by: pgshard-operator
type: Opaque
