apiVersion: v1
kind: Secret
metadata:
  name: webhook-certificate
  namespace: system
  labels:
    app.kubernetes.io/name: pgshard-operator
    app.kubernetes.io/component: admission
    app.kubernetes.io/managed-by: pgshard-operator
type: Opaque
