apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
  - name: vpostgresqlpodmetadata.pgshard.io
    objectSelector:
      matchLabels:
        app.kubernetes.io/component: postgresql
        app.kubernetes.io/managed-by: pgshard-operator
  - name: vpostgresqlfencingnamespace.pgshard.io
    objectSelector:
      matchLabels:
        pgshard.io/pod-fencing: enabled
  - name: vpostgresqlpodstatus.pgshard.io
    objectSelector:
      matchLabels:
        app.kubernetes.io/component: postgresql
        app.kubernetes.io/managed-by: pgshard-operator
  - name: vpostgresqlpodbinding.pgshard.io
    namespaceSelector:
      matchLabels:
        pgshard.io/pod-fencing: enabled
  - name: vpostgresqlpodcreate.pgshard.io
    namespaceSelector:
      matchLabels:
        pgshard.io/pod-fencing: enabled
  - name: vpostgresqlworkload.pgshard.io
    namespaceSelector:
      matchLabels:
        pgshard.io/pod-fencing: enabled
