apiVersion: v1
kind: Namespace
metadata:
  name: objectstores
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: azurite
  namespace: objectstores
spec:
  replicas: 1
  selector:
    matchLabels: {app: azurite}
  template:
    metadata:
      labels: {app: azurite}
    spec:
      containers:
        - name: azurite
          image: mcr.microsoft.com/azure-storage/azurite:3.36.0
          args: ["azurite-blob", "--blobHost", "0.0.0.0", "--blobPort", "10000", "--disableProductStyleUrl"]
          ports:
            - {containerPort: 10000, name: blob}
---
apiVersion: v1
kind: Service
metadata:
  name: azurite
  namespace: objectstores
spec:
  selector: {app: azurite}
  ports:
    - {name: blob, port: 10000, targetPort: 10000}
