-- Generated by pgshard-operator. Manual edits are overwritten.
SET LOCAL search_path = pg_catalog;
SELECT pg_catalog.count(*) FROM pgshard_catalog.install_database_genesis('analytics'::pgshard_catalog.sql_identifier, ARRAY[2,0]::bigint[]);
SELECT pg_catalog.count(*) FROM pgshard_catalog.install_database_genesis('app'::pgshard_catalog.sql_identifier, ARRAY[0,1,2,3]::bigint[]);
SELECT pg_catalog.count(*) FROM pgshard_catalog.install_database_genesis('billing'::pgshard_catalog.sql_identifier, ARRAY[0,1]::bigint[]);
DO $pgshard_database_genesis_postcondition$
BEGIN
  IF EXISTS (
      SELECT FROM pgshard_catalog.logical_databases AS databases
       WHERE databases.state <> 'retired'
         AND NOT (databases.database_name::text = ANY (ARRAY['analytics','app','billing']::text[]))
  ) THEN
    RAISE EXCEPTION USING ERRCODE = '22023', MESSAGE = 'database genesis contains an undeclared active logical database';
  END IF;
END
$pgshard_database_genesis_postcondition$;
