-- Generated by pgshard-operator. Manual edits are overwritten.
DO $pgshard_database_topology_preflight$
DECLARE
  topology_mismatch boolean;
BEGIN
  PERFORM state.catalog_epoch FROM pgshard_catalog.cluster_state AS state WHERE state.singleton FOR UPDATE;
  IF NOT FOUND THEN
    RAISE EXCEPTION USING ERRCODE = '55000', MESSAGE = 'shardschema cluster state singleton is missing';
  END IF;
  IF EXISTS (SELECT FROM pg_catalog.pg_attribute AS attributes WHERE attributes.attrelid = 'pgshard_catalog.routing_ranges'::pg_catalog.regclass AND attributes.attname = 'shard_id' AND attributes.attnum > 0 AND NOT attributes.attisdropped) THEN
    EXECUTE $pgshard_legacy_topology$SELECT EXISTS (
  WITH expected_databases(database_name, shard_numbers) AS (
    VALUES
      ('analytics'::text, ARRAY[2,0]::bigint[]),
      ('app'::text, ARRAY[0,1,2,3]::bigint[]),
      ('billing'::text, ARRAY[0,1]::bigint[])
  ), expected_cells AS (
    SELECT databases.database_name, cells.ordinality::bigint AS range_ordinal, cells.shard_number
      FROM expected_databases AS databases
      CROSS JOIN LATERAL pg_catalog.unnest(databases.shard_numbers) WITH ORDINALITY AS cells(shard_number, ordinality)
  ), expected_ranges AS (
    SELECT database_name, range_ordinal,
           pg_catalog.floor(((range_ordinal - 1)::numeric * 18446744073709551616) / pg_catalog.count(*) OVER (PARTITION BY database_name)) AS range_start,
           pg_catalog.floor((range_ordinal::numeric * 18446744073709551616) / pg_catalog.count(*) OVER (PARTITION BY database_name)) AS range_end,
           shard_number
      FROM expected_cells
  ), actual_topology_state AS (
    SELECT NOT EXISTS (SELECT FROM ONLY pgshard_catalog.logical_databases)
       AND NOT EXISTS (SELECT FROM ONLY pgshard_catalog.routing_epochs)
       AND NOT EXISTS (SELECT FROM ONLY pgshard_catalog.routing_ranges)
           AS is_empty
  ), actual_databases AS MATERIALIZED (
    SELECT databases.logical_database_id, databases.database_name, databases.state
      FROM ONLY pgshard_catalog.logical_databases AS databases
     WHERE databases.state <> 'retired'
     LIMIT 4
  ), active_epoch_counts AS (
    SELECT epochs.logical_database_id, pg_catalog.count(*) AS active_epoch_count
      FROM ONLY pgshard_catalog.routing_epochs AS epochs
      JOIN actual_databases AS databases USING (logical_database_id)
     WHERE epochs.state = 'active'
     GROUP BY epochs.logical_database_id
  ), actual_range_sample AS MATERIALIZED (
    SELECT databases.logical_database_id, databases.database_name::text AS database_name,
           ranges.range_start, ranges.range_end, shards.shard_number,
           databases.state AS database_state, epochs.state AS routing_state,
           epochs.logical_database_id = databases.logical_database_id AS routing_is_owned,
           NULL::bigint AS database_shard_ordinal, 'active'::text AS database_shard_state,
           1::bigint AS active_placement_count,
           shards.state AS shard_state, COALESCE(active_counts.active_epoch_count, 0) AS active_epoch_count
      FROM actual_databases AS databases
      LEFT JOIN ONLY pgshard_catalog.active_routing_epochs AS active ON active.logical_database_id = databases.logical_database_id
      LEFT JOIN ONLY pgshard_catalog.routing_epochs AS epochs ON epochs.routing_epoch = active.routing_epoch
      LEFT JOIN ONLY pgshard_catalog.routing_ranges AS ranges ON ranges.routing_epoch = active.routing_epoch
      LEFT JOIN ONLY pgshard_catalog.shards AS shards ON shards.shard_id = ranges.shard_id
      LEFT JOIN active_epoch_counts AS active_counts ON active_counts.logical_database_id = databases.logical_database_id
     LIMIT 9
  ), actual_ranges AS (
    SELECT sample.database_name,
           pg_catalog.row_number() OVER (PARTITION BY sample.logical_database_id ORDER BY sample.range_start, sample.range_end)::bigint AS range_ordinal,
           sample.range_start, sample.range_end, sample.shard_number, sample.database_state,
           sample.routing_state, sample.routing_is_owned, sample.database_shard_ordinal,
           sample.database_shard_state,
           sample.active_placement_count, sample.shard_state, sample.active_epoch_count
      FROM actual_range_sample AS sample
  ), mismatch AS (
    SELECT 1 WHERE (SELECT pg_catalog.count(*) FROM actual_databases) > 3
    UNION ALL
    SELECT 1 WHERE (SELECT pg_catalog.count(*) FROM actual_range_sample) > 8
    UNION ALL
    SELECT 1 WHERE NOT EXISTS (SELECT FROM expected_databases)
                   AND NOT (SELECT is_empty FROM actual_topology_state)
    UNION ALL
    SELECT 1
      FROM expected_ranges
      FULL JOIN actual_ranges USING (database_name, range_ordinal)
     WHERE (NOT COALESCE(pg_catalog.current_setting('pgshard.bootstrap_allow_empty_database_topology', true)::boolean, false)
            OR NOT (SELECT is_empty FROM actual_topology_state))
       AND (expected_ranges.range_start IS DISTINCT FROM actual_ranges.range_start
         OR expected_ranges.range_end IS DISTINCT FROM actual_ranges.range_end
         OR expected_ranges.shard_number IS DISTINCT FROM actual_ranges.shard_number
         OR actual_ranges.database_state IS DISTINCT FROM 'active'
         OR actual_ranges.routing_state IS DISTINCT FROM 'active'
         OR actual_ranges.routing_is_owned IS DISTINCT FROM true
         OR actual_ranges.database_shard_state IS DISTINCT FROM 'active'
         OR actual_ranges.active_placement_count IS DISTINCT FROM 1
         OR actual_ranges.shard_state IS DISTINCT FROM 'active'
         OR actual_ranges.active_epoch_count IS DISTINCT FROM 1)
    UNION ALL
    SELECT 1
      FROM expected_databases
      JOIN ONLY pgshard_catalog.logical_databases AS databases ON databases.database_name::text = expected_databases.database_name
     WHERE databases.state = 'retired'
  )
  SELECT FROM mismatch
)$pgshard_legacy_topology$ INTO topology_mismatch;
  ELSE
    EXECUTE $pgshard_placement_topology$SELECT EXISTS (
  WITH expected_databases(database_name, shard_numbers) AS (
    VALUES
      ('analytics'::text, ARRAY[2,0]::bigint[]),
      ('app'::text, ARRAY[0,1,2,3]::bigint[]),
      ('billing'::text, ARRAY[0,1]::bigint[])
  ), expected_cells AS (
    SELECT databases.database_name, cells.ordinality::bigint AS range_ordinal, cells.shard_number
      FROM expected_databases AS databases
      CROSS JOIN LATERAL pg_catalog.unnest(databases.shard_numbers) WITH ORDINALITY AS cells(shard_number, ordinality)
  ), expected_ranges AS (
    SELECT database_name, range_ordinal,
           pg_catalog.floor(((range_ordinal - 1)::numeric * 18446744073709551616) / pg_catalog.count(*) OVER (PARTITION BY database_name)) AS range_start,
           pg_catalog.floor((range_ordinal::numeric * 18446744073709551616) / pg_catalog.count(*) OVER (PARTITION BY database_name)) AS range_end,
           shard_number
      FROM expected_cells
  ), actual_topology_state AS (
    SELECT NOT EXISTS (SELECT FROM ONLY pgshard_catalog.logical_databases)
       AND NOT EXISTS (SELECT FROM ONLY pgshard_catalog.routing_epochs)
       AND NOT EXISTS (SELECT FROM ONLY pgshard_catalog.routing_ranges)
       AND NOT EXISTS (SELECT FROM ONLY pgshard_catalog.database_shards)
       AND NOT EXISTS (SELECT FROM ONLY pgshard_catalog.database_shard_placements)
           AS is_empty
  ), actual_databases AS MATERIALIZED (
    SELECT databases.logical_database_id, databases.database_name, databases.state
      FROM ONLY pgshard_catalog.logical_databases AS databases
     WHERE databases.state <> 'retired'
     LIMIT 4
  ), active_epoch_counts AS (
    SELECT epochs.logical_database_id, pg_catalog.count(*) AS active_epoch_count
      FROM ONLY pgshard_catalog.routing_epochs AS epochs
      JOIN actual_databases AS databases USING (logical_database_id)
     WHERE epochs.state = 'active'
     GROUP BY epochs.logical_database_id
  ), actual_range_sample AS MATERIALIZED (
    SELECT databases.logical_database_id, databases.database_name::text AS database_name,
           ranges.range_start, ranges.range_end, shards.shard_number,
           databases.state AS database_state, epochs.state AS routing_state,
           epochs.logical_database_id = databases.logical_database_id AS routing_is_owned,
           database_shards.shard_ordinal AS database_shard_ordinal, database_shards.state AS database_shard_state,
           placement_counts.active_placement_count,
           shards.state AS shard_state, COALESCE(active_counts.active_epoch_count, 0) AS active_epoch_count
      FROM actual_databases AS databases
      LEFT JOIN ONLY pgshard_catalog.active_routing_epochs AS active ON active.logical_database_id = databases.logical_database_id
      LEFT JOIN ONLY pgshard_catalog.routing_epochs AS epochs ON epochs.routing_epoch = active.routing_epoch
      LEFT JOIN ONLY pgshard_catalog.routing_ranges AS ranges ON ranges.logical_database_id = databases.logical_database_id AND ranges.routing_epoch = active.routing_epoch
      LEFT JOIN ONLY pgshard_catalog.database_shards AS database_shards ON database_shards.logical_database_id = ranges.logical_database_id AND database_shards.database_shard_id = ranges.database_shard_id
      LEFT JOIN LATERAL (SELECT pg_catalog.count(*) AS active_placement_count FROM ONLY pgshard_catalog.database_shard_placements AS counted WHERE counted.logical_database_id = ranges.logical_database_id AND counted.database_shard_id = ranges.database_shard_id AND counted.state = 'active') AS placement_counts ON true
      LEFT JOIN ONLY pgshard_catalog.database_shard_placements AS placements ON placements.logical_database_id = ranges.logical_database_id AND placements.database_shard_id = ranges.database_shard_id AND placements.state = 'active'
      LEFT JOIN ONLY pgshard_catalog.shards AS shards ON shards.shard_id = placements.shard_id
      LEFT JOIN active_epoch_counts AS active_counts ON active_counts.logical_database_id = databases.logical_database_id
     LIMIT 9
  ), actual_ranges AS (
    SELECT sample.database_name,
           pg_catalog.row_number() OVER (PARTITION BY sample.logical_database_id ORDER BY sample.range_start, sample.range_end)::bigint AS range_ordinal,
           sample.range_start, sample.range_end, sample.shard_number, sample.database_state,
           sample.routing_state, sample.routing_is_owned, sample.database_shard_ordinal,
           sample.database_shard_state,
           sample.active_placement_count, sample.shard_state, sample.active_epoch_count
      FROM actual_range_sample AS sample
  ), mismatch AS (
    SELECT 1 WHERE (SELECT pg_catalog.count(*) FROM actual_databases) > 3
    UNION ALL
    SELECT 1 WHERE (SELECT pg_catalog.count(*) FROM actual_range_sample) > 8
    UNION ALL
    SELECT 1 WHERE NOT EXISTS (SELECT FROM expected_databases)
                   AND NOT (SELECT is_empty FROM actual_topology_state)
    UNION ALL
    SELECT 1
      FROM expected_ranges
      FULL JOIN actual_ranges USING (database_name, range_ordinal)
     WHERE (NOT COALESCE(pg_catalog.current_setting('pgshard.bootstrap_allow_empty_database_topology', true)::boolean, false)
            OR NOT (SELECT is_empty FROM actual_topology_state))
       AND (expected_ranges.range_start IS DISTINCT FROM actual_ranges.range_start
         OR expected_ranges.range_end IS DISTINCT FROM actual_ranges.range_end
         OR expected_ranges.shard_number IS DISTINCT FROM actual_ranges.shard_number
         OR actual_ranges.database_state IS DISTINCT FROM 'active'
         OR actual_ranges.routing_state IS DISTINCT FROM 'active'
         OR actual_ranges.routing_is_owned IS DISTINCT FROM true
         OR actual_ranges.database_shard_ordinal IS DISTINCT FROM expected_ranges.range_ordinal - 1
         OR actual_ranges.database_shard_state IS DISTINCT FROM 'active'
         OR actual_ranges.active_placement_count IS DISTINCT FROM 1
         OR actual_ranges.shard_state IS DISTINCT FROM 'active'
         OR actual_ranges.active_epoch_count IS DISTINCT FROM 1)
    UNION ALL
    SELECT 1
      FROM expected_databases
      JOIN ONLY pgshard_catalog.logical_databases AS databases ON databases.database_name::text = expected_databases.database_name
     WHERE databases.state = 'retired'
  )
  SELECT FROM mismatch
)$pgshard_placement_topology$ INTO topology_mismatch;
  END IF;
  IF topology_mismatch THEN
    RAISE EXCEPTION USING ERRCODE = '22023', MESSAGE = 'RestoreTopologyMismatch: shardschema logical database topology conflicts with configured immutable database genesis';
  END IF;
END
$pgshard_database_topology_preflight$;
