"""Emits internal/router/plan/builtins.go from the pg_proc.dat of each major."""

import re
import sys


def entries(text):
    depth, buf = 0, []
    for ch in text:
        if ch == "{":
            depth += 1
            if depth == 1:
                buf = []
        if depth:
            buf.append(ch)
        if ch == "}":
            depth -= 1
            if depth == 0:
                yield "".join(buf)


def read(path):
    aggregates, functions = set(), set()
    with open(path, encoding="utf-8") as fh:
        text = fh.read()
    for entry in entries(text):
        name = re.search(r"proname\s*=>\s*'([^']*)'", entry)
        if not name:
            continue
        kind = re.search(r"prokind\s*=>\s*'([^']*)'", entry)
        kind = kind.group(1) if kind else "f"
        # A window function collapses nothing, but a scatter cannot compute
        # one either, so it is recognised alongside the aggregates.
        (aggregates if kind in ("a", "w") else functions).add(name.group(1))
    return aggregates, functions


def block(names):
    return "\n".join(sorted(names))


def main():
    aggregates, functions = set(), set()
    for path in sys.argv[1:]:
        a, f = read(path)
        aggregates |= a
        functions |= f
    functions -= aggregates
    sys.stdout.write(f'''// Code generated by hack/gen-builtins.sh; DO NOT EDIT.

package plan

// The planner tells an aggregate from a scalar function by name: it parses
// with libpg_query and never asks a shard what a function is. These are
// every proname in the pg_proc.dat of the majors pgshard targets, so a
// name in neither set is user-defined or comes from an extension -- and a
// user-defined aggregate cannot be told from a user-defined scalar, which
// is why a scatter refuses one rather than concatenating a partial row per
// shard.

// builtinAggregateNames are the aggregate and window functions (prokind a
// and w).
const builtinAggregateNames = `{block(aggregates)}`

// builtinFunctionNames are the rest (prokind f and p).
const builtinFunctionNames = `{block(functions)}`
''')


if __name__ == "__main__":
    main()
