local postgres,shardschema postgres peer
local shardschema pgshard_pooler_catalog scram-sha-256
local shardschema pgshard_orchestrator_catalog scram-sha-256
local all all reject
local replication all reject
