//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/api/core/v1"
	networkingv1 "k8s.io/api/networking/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AdminSpec) DeepCopyInto(out *AdminSpec) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdminSpec.
func (in *AdminSpec) DeepCopy() *AdminSpec {
	if in == nil {
		return nil
	}
	out := new(AdminSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackupRetention) DeepCopyInto(out *BackupRetention) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackupRetention.
func (in *BackupRetention) DeepCopy() *BackupRetention {
	if in == nil {
		return nil
	}
	out := new(BackupRetention)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackupSchedules) DeepCopyInto(out *BackupSchedules) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackupSchedules.
func (in *BackupSchedules) DeepCopy() *BackupSchedules {
	if in == nil {
		return nil
	}
	out := new(BackupSchedules)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackupSpec) DeepCopyInto(out *BackupSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackupSpec.
func (in *BackupSpec) DeepCopy() *BackupSpec {
	if in == nil {
		return nil
	}
	out := new(BackupSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CatalogSpec) DeepCopyInto(out *CatalogSpec) {
	*out = *in
	in.Storage.DeepCopyInto(&out.Storage)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CatalogSpec.
func (in *CatalogSpec) DeepCopy() *CatalogSpec {
	if in == nil {
		return nil
	}
	out := new(CatalogSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterBackupStatus) DeepCopyInto(out *ClusterBackupStatus) {
	*out = *in
	if in.LastFullTime != nil {
		in, out := &in.LastFullTime, &out.LastFullTime
		*out = (*in).DeepCopy()
	}
	if in.LastDifferentialTime != nil {
		in, out := &in.LastDifferentialTime, &out.LastDifferentialTime
		*out = (*in).DeepCopy()
	}
	if in.LastIncrementalTime != nil {
		in, out := &in.LastIncrementalTime, &out.LastIncrementalTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterBackupStatus.
func (in *ClusterBackupStatus) DeepCopy() *ClusterBackupStatus {
	if in == nil {
		return nil
	}
	out := new(ClusterBackupStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterCatalogUpgradeStatus) DeepCopyInto(out *ClusterCatalogUpgradeStatus) {
	*out = *in
	if in.Blockers != nil {
		in, out := &in.Blockers, &out.Blockers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.SwitchedAt != nil {
		in, out := &in.SwitchedAt, &out.SwitchedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterCatalogUpgradeStatus.
func (in *ClusterCatalogUpgradeStatus) DeepCopy() *ClusterCatalogUpgradeStatus {
	if in == nil {
		return nil
	}
	out := new(ClusterCatalogUpgradeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterPlacementWorkflowStatus) DeepCopyInto(out *ClusterPlacementWorkflowStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterPlacementWorkflowStatus.
func (in *ClusterPlacementWorkflowStatus) DeepCopy() *ClusterPlacementWorkflowStatus {
	if in == nil {
		return nil
	}
	out := new(ClusterPlacementWorkflowStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterReshardStatus) DeepCopyInto(out *ClusterReshardStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterReshardStatus.
func (in *ClusterReshardStatus) DeepCopy() *ClusterReshardStatus {
	if in == nil {
		return nil
	}
	out := new(ClusterReshardStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DerivedSetting) DeepCopyInto(out *DerivedSetting) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DerivedSetting.
func (in *DerivedSetting) DeepCopy() *DerivedSetting {
	if in == nil {
		return nil
	}
	out := new(DerivedSetting)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DurabilitySpec) DeepCopyInto(out *DurabilitySpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DurabilitySpec.
func (in *DurabilitySpec) DeepCopy() *DurabilitySpec {
	if in == nil {
		return nil
	}
	out := new(DurabilitySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GroupBackupStatus) DeepCopyInto(out *GroupBackupStatus) {
	*out = *in
	if in.StartedAt != nil {
		in, out := &in.StartedAt, &out.StartedAt
		*out = (*in).DeepCopy()
	}
	if in.CompletedAt != nil {
		in, out := &in.CompletedAt, &out.CompletedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GroupBackupStatus.
func (in *GroupBackupStatus) DeepCopy() *GroupBackupStatus {
	if in == nil {
		return nil
	}
	out := new(GroupBackupStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GroupRestoreStatus) DeepCopyInto(out *GroupRestoreStatus) {
	*out = *in
	if in.PreparedTransactions != nil {
		in, out := &in.PreparedTransactions, &out.PreparedTransactions
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GroupRestoreStatus.
func (in *GroupRestoreStatus) DeepCopy() *GroupRestoreStatus {
	if in == nil {
		return nil
	}
	out := new(GroupRestoreStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GroupRollout) DeepCopyInto(out *GroupRollout) {
	*out = *in
	if in.Since != nil {
		in, out := &in.Since, &out.Since
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GroupRollout.
func (in *GroupRollout) DeepCopy() *GroupRollout {
	if in == nil {
		return nil
	}
	out := new(GroupRollout)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HPASpec) DeepCopyInto(out *HPASpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HPASpec.
func (in *HPASpec) DeepCopy() *HPASpec {
	if in == nil {
		return nil
	}
	out := new(HPASpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InternalTLSSpec) DeepCopyInto(out *InternalTLSSpec) {
	*out = *in
	if in.SecretRef != nil {
		in, out := &in.SecretRef, &out.SecretRef
		*out = new(v1.LocalObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InternalTLSSpec.
func (in *InternalTLSSpec) DeepCopy() *InternalTLSSpec {
	if in == nil {
		return nil
	}
	out := new(InternalTLSSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MemberStatus) DeepCopyInto(out *MemberStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MemberStatus.
func (in *MemberStatus) DeepCopy() *MemberStatus {
	if in == nil {
		return nil
	}
	out := new(MemberStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkPolicySpec) DeepCopyInto(out *NetworkPolicySpec) {
	*out = *in
	if in.Clients != nil {
		in, out := &in.Clients, &out.Clients
		*out = make([]networkingv1.NetworkPolicyPeer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkPolicySpec.
func (in *NetworkPolicySpec) DeepCopy() *NetworkPolicySpec {
	if in == nil {
		return nil
	}
	out := new(NetworkPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObjectStoreSpec) DeepCopyInto(out *ObjectStoreSpec) {
	*out = *in
	if in.VerifyTLS != nil {
		in, out := &in.VerifyTLS, &out.VerifyTLS
		*out = new(bool)
		**out = **in
	}
	in.Credentials.DeepCopyInto(&out.Credentials)
	in.Encryption.DeepCopyInto(&out.Encryption)
	if in.SFTP != nil {
		in, out := &in.SFTP, &out.SFTP
		*out = new(SFTPStoreSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObjectStoreSpec.
func (in *ObjectStoreSpec) DeepCopy() *ObjectStoreSpec {
	if in == nil {
		return nil
	}
	out := new(ObjectStoreSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PgShardBackup) DeepCopyInto(out *PgShardBackup) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PgShardBackup.
func (in *PgShardBackup) DeepCopy() *PgShardBackup {
	if in == nil {
		return nil
	}
	out := new(PgShardBackup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PgShardBackup) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PgShardBackupList) DeepCopyInto(out *PgShardBackupList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PgShardBackup, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PgShardBackupList.
func (in *PgShardBackupList) DeepCopy() *PgShardBackupList {
	if in == nil {
		return nil
	}
	out := new(PgShardBackupList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PgShardBackupList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PgShardBackupPolicy) DeepCopyInto(out *PgShardBackupPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PgShardBackupPolicy.
func (in *PgShardBackupPolicy) DeepCopy() *PgShardBackupPolicy {
	if in == nil {
		return nil
	}
	out := new(PgShardBackupPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PgShardBackupPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PgShardBackupPolicyList) DeepCopyInto(out *PgShardBackupPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PgShardBackupPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PgShardBackupPolicyList.
func (in *PgShardBackupPolicyList) DeepCopy() *PgShardBackupPolicyList {
	if in == nil {
		return nil
	}
	out := new(PgShardBackupPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PgShardBackupPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PgShardBackupPolicySpec) DeepCopyInto(out *PgShardBackupPolicySpec) {
	*out = *in
	in.ObjectStore.DeepCopyInto(&out.ObjectStore)
	out.Schedules = in.Schedules
	out.Retention = in.Retention
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PgShardBackupPolicySpec.
func (in *PgShardBackupPolicySpec) DeepCopy() *PgShardBackupPolicySpec {
	if in == nil {
		return nil
	}
	out := new(PgShardBackupPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PgShardBackupPolicyStatus) DeepCopyInto(out *PgShardBackupPolicyStatus) {
	*out = *in
	if in.Accepted != nil {
		in, out := &in.Accepted, &out.Accepted
		*out = new(PgShardBackupPolicySpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Clusters != nil {
		in, out := &in.Clusters, &out.Clusters
		*out = make([]ClusterBackupStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PgShardBackupPolicyStatus.
func (in *PgShardBackupPolicyStatus) DeepCopy() *PgShardBackupPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(PgShardBackupPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PgShardBackupSpec) DeepCopyInto(out *PgShardBackupSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PgShardBackupSpec.
func (in *PgShardBackupSpec) DeepCopy() *PgShardBackupSpec {
	if in == nil {
		return nil
	}
	out := new(PgShardBackupSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PgShardBackupStatus) DeepCopyInto(out *PgShardBackupStatus) {
	*out = *in
	if in.StartedAt != nil {
		in, out := &in.StartedAt, &out.StartedAt
		*out = (*in).DeepCopy()
	}
	if in.CompletedAt != nil {
		in, out := &in.CompletedAt, &out.CompletedAt
		*out = (*in).DeepCopy()
	}
	if in.Groups != nil {
		in, out := &in.Groups, &out.Groups
		*out = make([]GroupBackupStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PgShardBackupStatus.
func (in *PgShardBackupStatus) DeepCopy() *PgShardBackupStatus {
	if in == nil {
		return nil
	}
	out := new(PgShardBackupStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PgShardCluster) DeepCopyInto(out *PgShardCluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PgShardCluster.
func (in *PgShardCluster) DeepCopy() *PgShardCluster {
	if in == nil {
		return nil
	}
	out := new(PgShardCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PgShardCluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PgShardClusterList) DeepCopyInto(out *PgShardClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PgShardCluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PgShardClusterList.
func (in *PgShardClusterList) DeepCopy() *PgShardClusterList {
	if in == nil {
		return nil
	}
	out := new(PgShardClusterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PgShardClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PgShardClusterSpec) DeepCopyInto(out *PgShardClusterSpec) {
	*out = *in
	in.PostgreSQL.DeepCopyInto(&out.PostgreSQL)
	in.Resources.DeepCopyInto(&out.Resources)
	in.Catalog.DeepCopyInto(&out.Catalog)
	if in.Shards != nil {
		in, out := &in.Shards, &out.Shards
		*out = new(int)
		**out = **in
	}
	in.Storage.DeepCopyInto(&out.Storage)
	out.Durability = in.Durability
	in.Router.DeepCopyInto(&out.Router)
	in.Admin.DeepCopyInto(&out.Admin)
	in.Placement.DeepCopyInto(&out.Placement)
	out.Backup = in.Backup
	in.NetworkPolicy.DeepCopyInto(&out.NetworkPolicy)
	in.Resharding.DeepCopyInto(&out.Resharding)
	out.Upgrade = in.Upgrade
	in.InternalTLS.DeepCopyInto(&out.InternalTLS)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PgShardClusterSpec.
func (in *PgShardClusterSpec) DeepCopy() *PgShardClusterSpec {
	if in == nil {
		return nil
	}
	out := new(PgShardClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PgShardClusterStatus) DeepCopyInto(out *PgShardClusterStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Shards != nil {
		in, out := &in.Shards, &out.Shards
		*out = make([]ShardStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Reshard != nil {
		in, out := &in.Reshard, &out.Reshard
		*out = new(ClusterReshardStatus)
		**out = **in
	}
	if in.CatalogUpgrade != nil {
		in, out := &in.CatalogUpgrade, &out.CatalogUpgrade
		*out = new(ClusterCatalogUpgradeStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.PlacementWorkflows != nil {
		in, out := &in.PlacementWorkflows, &out.PlacementWorkflows
		*out = make([]ClusterPlacementWorkflowStatus, len(*in))
		copy(*out, *in)
	}
	in.Tuning.DeepCopyInto(&out.Tuning)
	out.Rollout = in.Rollout
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PgShardClusterStatus.
func (in *PgShardClusterStatus) DeepCopy() *PgShardClusterStatus {
	if in == nil {
		return nil
	}
	out := new(PgShardClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PgShardGroup) DeepCopyInto(out *PgShardGroup) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PgShardGroup.
func (in *PgShardGroup) DeepCopy() *PgShardGroup {
	if in == nil {
		return nil
	}
	out := new(PgShardGroup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PgShardGroup) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PgShardGroupList) DeepCopyInto(out *PgShardGroupList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PgShardGroup, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PgShardGroupList.
func (in *PgShardGroupList) DeepCopy() *PgShardGroupList {
	if in == nil {
		return nil
	}
	out := new(PgShardGroupList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PgShardGroupList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PgShardGroupSpec) DeepCopyInto(out *PgShardGroupSpec) {
	*out = *in
	if in.ShardID != nil {
		in, out := &in.ShardID, &out.ShardID
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PgShardGroupSpec.
func (in *PgShardGroupSpec) DeepCopy() *PgShardGroupSpec {
	if in == nil {
		return nil
	}
	out := new(PgShardGroupSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PgShardGroupStatus) DeepCopyInto(out *PgShardGroupStatus) {
	*out = *in
	if in.Members != nil {
		in, out := &in.Members, &out.Members
		*out = make([]MemberStatus, len(*in))
		copy(*out, *in)
	}
	if in.Rollout != nil {
		in, out := &in.Rollout, &out.Rollout
		*out = new(GroupRollout)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PgShardGroupStatus.
func (in *PgShardGroupStatus) DeepCopy() *PgShardGroupStatus {
	if in == nil {
		return nil
	}
	out := new(PgShardGroupStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PgShardReshard) DeepCopyInto(out *PgShardReshard) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PgShardReshard.
func (in *PgShardReshard) DeepCopy() *PgShardReshard {
	if in == nil {
		return nil
	}
	out := new(PgShardReshard)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PgShardReshard) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PgShardReshardList) DeepCopyInto(out *PgShardReshardList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PgShardReshard, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PgShardReshardList.
func (in *PgShardReshardList) DeepCopy() *PgShardReshardList {
	if in == nil {
		return nil
	}
	out := new(PgShardReshardList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PgShardReshardList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PgShardReshardSpec) DeepCopyInto(out *PgShardReshardSpec) {
	*out = *in
	if in.TargetRanges != nil {
		in, out := &in.TargetRanges, &out.TargetRanges
		*out = make([]ReshardRange, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PgShardReshardSpec.
func (in *PgShardReshardSpec) DeepCopy() *PgShardReshardSpec {
	if in == nil {
		return nil
	}
	out := new(PgShardReshardSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PgShardReshardStatus) DeepCopyInto(out *PgShardReshardStatus) {
	*out = *in
	if in.Targets != nil {
		in, out := &in.Targets, &out.Targets
		*out = make([]ReshardTargetStatus, len(*in))
		copy(*out, *in)
	}
	if in.JournalIDs != nil {
		in, out := &in.JournalIDs, &out.JournalIDs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.CutoverPause != nil {
		in, out := &in.CutoverPause, &out.CutoverPause
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PgShardReshardStatus.
func (in *PgShardReshardStatus) DeepCopy() *PgShardReshardStatus {
	if in == nil {
		return nil
	}
	out := new(PgShardReshardStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PgShardRestore) DeepCopyInto(out *PgShardRestore) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PgShardRestore.
func (in *PgShardRestore) DeepCopy() *PgShardRestore {
	if in == nil {
		return nil
	}
	out := new(PgShardRestore)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PgShardRestore) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PgShardRestoreList) DeepCopyInto(out *PgShardRestoreList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PgShardRestore, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PgShardRestoreList.
func (in *PgShardRestoreList) DeepCopy() *PgShardRestoreList {
	if in == nil {
		return nil
	}
	out := new(PgShardRestoreList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PgShardRestoreList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PgShardRestoreSpec) DeepCopyInto(out *PgShardRestoreSpec) {
	*out = *in
	if in.ClusterSpec != nil {
		in, out := &in.ClusterSpec, &out.ClusterSpec
		*out = new(PgShardClusterSpec)
		(*in).DeepCopyInto(*out)
	}
	in.Target.DeepCopyInto(&out.Target)
	if in.TargetTLI != nil {
		in, out := &in.TargetTLI, &out.TargetTLI
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PgShardRestoreSpec.
func (in *PgShardRestoreSpec) DeepCopy() *PgShardRestoreSpec {
	if in == nil {
		return nil
	}
	out := new(PgShardRestoreSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PgShardRestoreStatus) DeepCopyInto(out *PgShardRestoreStatus) {
	*out = *in
	if in.StartedAt != nil {
		in, out := &in.StartedAt, &out.StartedAt
		*out = (*in).DeepCopy()
	}
	if in.CompletedAt != nil {
		in, out := &in.CompletedAt, &out.CompletedAt
		*out = (*in).DeepCopy()
	}
	if in.Groups != nil {
		in, out := &in.Groups, &out.Groups
		*out = make([]GroupRestoreStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Reconciliation != nil {
		in, out := &in.Reconciliation, &out.Reconciliation
		*out = new(RestoreReconciliationStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PgShardRestoreStatus.
func (in *PgShardRestoreStatus) DeepCopy() *PgShardRestoreStatus {
	if in == nil {
		return nil
	}
	out := new(PgShardRestoreStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlacementSpec) DeepCopyInto(out *PlacementSpec) {
	*out = *in
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]v1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Affinity != nil {
		in, out := &in.Affinity, &out.Affinity
		*out = new(v1.Affinity)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlacementSpec.
func (in *PlacementSpec) DeepCopy() *PlacementSpec {
	if in == nil {
		return nil
	}
	out := new(PlacementSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostgreSQLSpec) DeepCopyInto(out *PostgreSQLSpec) {
	*out = *in
	if in.Parameters != nil {
		in, out := &in.Parameters, &out.Parameters
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostgreSQLSpec.
func (in *PostgreSQLSpec) DeepCopy() *PostgreSQLSpec {
	if in == nil {
		return nil
	}
	out := new(PostgreSQLSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReshardRange) DeepCopyInto(out *ReshardRange) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReshardRange.
func (in *ReshardRange) DeepCopy() *ReshardRange {
	if in == nil {
		return nil
	}
	out := new(ReshardRange)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReshardTargetStatus) DeepCopyInto(out *ReshardTargetStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReshardTargetStatus.
func (in *ReshardTargetStatus) DeepCopy() *ReshardTargetStatus {
	if in == nil {
		return nil
	}
	out := new(ReshardTargetStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReshardingSpec) DeepCopyInto(out *ReshardingSpec) {
	*out = *in
	if in.RetireOldGroupsAfter != nil {
		in, out := &in.RetireOldGroupsAfter, &out.RetireOldGroupsAfter
		*out = new(metav1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReshardingSpec.
func (in *ReshardingSpec) DeepCopy() *ReshardingSpec {
	if in == nil {
		return nil
	}
	out := new(ReshardingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RestoreReconciliationStatus) DeepCopyInto(out *RestoreReconciliationStatus) {
	*out = *in
	if in.Contradictions != nil {
		in, out := &in.Contradictions, &out.Contradictions
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Unverifiable != nil {
		in, out := &in.Unverifiable, &out.Unverifiable
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Unreadable != nil {
		in, out := &in.Unreadable, &out.Unreadable
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RestoreReconciliationStatus.
func (in *RestoreReconciliationStatus) DeepCopy() *RestoreReconciliationStatus {
	if in == nil {
		return nil
	}
	out := new(RestoreReconciliationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RestoreTarget) DeepCopyInto(out *RestoreTarget) {
	*out = *in
	if in.Time != nil {
		in, out := &in.Time, &out.Time
		*out = (*in).DeepCopy()
	}
	if in.LSN != nil {
		in, out := &in.LSN, &out.LSN
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.XID != nil {
		in, out := &in.XID, &out.XID
		*out = new(string)
		**out = **in
	}
	if in.Immediate != nil {
		in, out := &in.Immediate, &out.Immediate
		*out = new(bool)
		**out = **in
	}
	if in.Barrier != nil {
		in, out := &in.Barrier, &out.Barrier
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RestoreTarget.
func (in *RestoreTarget) DeepCopy() *RestoreTarget {
	if in == nil {
		return nil
	}
	out := new(RestoreTarget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RolloutStatus) DeepCopyInto(out *RolloutStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RolloutStatus.
func (in *RolloutStatus) DeepCopy() *RolloutStatus {
	if in == nil {
		return nil
	}
	out := new(RolloutStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RouterSpec) DeepCopyInto(out *RouterSpec) {
	*out = *in
	out.HPA = in.HPA
	in.TLS.DeepCopyInto(&out.TLS)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RouterSpec.
func (in *RouterSpec) DeepCopy() *RouterSpec {
	if in == nil {
		return nil
	}
	out := new(RouterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SFTPStoreSpec) DeepCopyInto(out *SFTPStoreSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SFTPStoreSpec.
func (in *SFTPStoreSpec) DeepCopy() *SFTPStoreSpec {
	if in == nil {
		return nil
	}
	out := new(SFTPStoreSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretRefSpec) DeepCopyInto(out *SecretRefSpec) {
	*out = *in
	if in.SecretRef != nil {
		in, out := &in.SecretRef, &out.SecretRef
		*out = new(v1.LocalObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretRefSpec.
func (in *SecretRefSpec) DeepCopy() *SecretRefSpec {
	if in == nil {
		return nil
	}
	out := new(SecretRefSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ShardStatus) DeepCopyInto(out *ShardStatus) {
	*out = *in
	if in.Members != nil {
		in, out := &in.Members, &out.Members
		*out = make([]MemberStatus, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ShardStatus.
func (in *ShardStatus) DeepCopy() *ShardStatus {
	if in == nil {
		return nil
	}
	out := new(ShardStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageSpec) DeepCopyInto(out *StorageSpec) {
	*out = *in
	out.Size = in.Size.DeepCopy()
	if in.StorageClassName != nil {
		in, out := &in.StorageClassName, &out.StorageClassName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageSpec.
func (in *StorageSpec) DeepCopy() *StorageSpec {
	if in == nil {
		return nil
	}
	out := new(StorageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TLSSpec) DeepCopyInto(out *TLSSpec) {
	*out = *in
	if in.SecretRef != nil {
		in, out := &in.SecretRef, &out.SecretRef
		*out = new(v1.LocalObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TLSSpec.
func (in *TLSSpec) DeepCopy() *TLSSpec {
	if in == nil {
		return nil
	}
	out := new(TLSSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TuningStatus) DeepCopyInto(out *TuningStatus) {
	*out = *in
	if in.Derived != nil {
		in, out := &in.Derived, &out.Derived
		*out = make([]DerivedSetting, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TuningStatus.
func (in *TuningStatus) DeepCopy() *TuningStatus {
	if in == nil {
		return nil
	}
	out := new(TuningStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpgradeSpec) DeepCopyInto(out *UpgradeSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpgradeSpec.
func (in *UpgradeSpec) DeepCopy() *UpgradeSpec {
	if in == nil {
		return nil
	}
	out := new(UpgradeSpec)
	in.DeepCopyInto(out)
	return out
}
