apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pgshard-system
namePrefix: pgshard-
resources:
  - ../namespace
  - ../crd
  - ../rbac
  - ../manager
  - ../webhook
  - rbac
patches:
  - path: manager_patch.yaml
