apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: system
spec:
  progressDeadlineSeconds: 180
  template:
    spec:
      containers:
        - name: manager
          args:
            - --health-probe-bind-address=:8081
            - --metrics-bind-address=0
            - --leader-elect=true
            - --webhook-enabled=true
            - --webhook-namespace=$(POD_NAMESPACE)
            - --webhook-service-name=pgshard-webhook-service
            - --webhook-ca-secret-name=pgshard-webhook-ca
            - --webhook-serving-secret-name=pgshard-webhook-certificate
            - --webhook-fencing-key-secret-name=pgshard-webhook-fencing-key
            - --webhook-mutating-configuration-name=pgshard-mutating-webhook-configuration
            - --webhook-validating-configuration-name=pgshard-validating-webhook-configuration
            - --webhook-cert-dir=/run/pgshard/webhook
            - --orchestrator-image=pgshard/orchestrator:dev
            - --pooler-image=pgshard/pooler:dev
            - --postgresql-image=docker.io/library/postgres@sha256:311136771dca6826c3b6e691ebf8cb6e896e165074bc57a728f9619f25f0c4c7
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          ports:
            - name: webhook
              containerPort: 9443
              protocol: TCP
          startupProbe:
            failureThreshold: 75
          volumeMounts:
            - name: webhook-certificates
              mountPath: /run/pgshard
      volumes:
        - name: webhook-certificates
          emptyDir:
            medium: Memory
            sizeLimit: 16Mi
