//! Live `PostgreSQL` 18 proof that the synchronous topology is reloadable.

use std::fs::{self, OpenOptions};
use std::io::Write;
use std::net::{SocketAddr, TcpListener, TcpStream};
use std::os::unix::fs::{OpenOptionsExt, PermissionsExt};
use std::os::unix::process::CommandExt;
use std::path::{Path, PathBuf};
use std::process::{Child, Command, Stdio};
use std::thread;
use std::time::{Duration, Instant};

use rustix::process::{Pid, Signal, kill_process, kill_process_group};
use tempfile::TempDir;

const READY_TIMEOUT: Duration = Duration::from_secs(30);
const RELOAD_TIMEOUT: Duration = Duration::from_secs(10);
const LOCAL_TOPOLOGY: &str = "";
const REMOTE_TOPOLOGY: &str = "ANY 1 (pgshard_member_0001, pgshard_member_0002)";

struct AgentGuard {
    child: Option<Child>,
    process_group: Option<Pid>,
    stderr_path: PathBuf,
}

impl AgentGuard {
    fn stderr(&self) -> String {
        fs::read_to_string(&self.stderr_path).unwrap_or_default()
    }
}

impl Drop for AgentGuard {
    fn drop(&mut self) {
        if let Some(process_group) = self.process_group.take() {
            let _ = kill_process_group(process_group, Signal::KILL);
        }
        if let Some(mut child) = self.child.take() {
            let _ = child.wait();
        }
    }
}

/// `synchronous_standby_names` is `PGC_SIGHUP`, but a postmaster argument is
/// `PGC_S_ARGV`, which outranks the `PGC_S_FILE` a reload writes. Only a value
/// that reaches the postmaster through a configuration file can be replaced
/// while the postmaster keeps running, and keeping it running is the point: a
/// restart loses the writable generation the agent fences against.
#[tokio::test]
#[ignore = "requires PGSHARD_TEST_POSTGRES_BIN pointing at a PostgreSQL 18 bin directory"]
async fn the_synchronous_topology_changes_by_reload_without_restarting_the_postmaster() {
    let bin = PathBuf::from(
        std::env::var_os("PGSHARD_TEST_POSTGRES_BIN").expect("PGSHARD_TEST_POSTGRES_BIN"),
    );
    let root = TempDir::new().expect("create reload fixture");
    let data_dir = root.path().join("data");
    let synchronous_conf_file = root.path().join("conf").join("synchronous.conf");
    initialize_pgdata(&bin, &data_dir);

    let address = reserve_address();
    let agent = spawn_agent(
        &bin,
        root.path(),
        &data_dir,
        &synchronous_conf_file,
        address,
    );
    wait_for_quarantine(&agent, address);

    let postmaster = postmaster_pid(&data_dir);
    let arguments = command_line(postmaster);
    assert!(
        !arguments
            .iter()
            .any(|argument| argument.starts_with("synchronous_standby_names")),
        "the running postmaster pinned the topology on its command line: {arguments:?}"
    );
    assert!(
        arguments
            .iter()
            .any(|argument| argument == "allow_alter_system=off"),
        "the running postmaster left ALTER SYSTEM able to outrank the agent's file: {arguments:?}"
    );
    assert_eq!(
        fs::read_to_string(&synchronous_conf_file).expect("read materialized topology"),
        expected_conf(LOCAL_TOPOLOGY)
    );
    assert!(
        fs::read_to_string(data_dir.join("postgresql.conf"))
            .expect("read configuration")
            .ends_with(&format!(
                "\ninclude_if_exists '{}'\n",
                synchronous_conf_file.display()
            )),
        "the postmaster reads no other file, so an unincluded topology never reaches it"
    );

    for topology in [REMOTE_TOPOLOGY, LOCAL_TOPOLOGY] {
        install_topology(&synchronous_conf_file, topology);
        kill_process(
            Pid::from_raw(postmaster).expect("postmaster pid"),
            Signal::HUP,
        )
        .expect("reload the postmaster");
        let reported = format!(r#"parameter "synchronous_standby_names" changed to "{topology}""#);
        wait_for_stderr(&agent, &reported);
        assert_eq!(
            postmaster_pid(&data_dir),
            postmaster,
            "the topology changed by restart, which would have lost the writable generation"
        );
    }
}

fn expected_conf(topology: &str) -> String {
    format!(
        "# Generated by pgshard-agent. Manual edits are overwritten.\n\
         synchronous_standby_names = '{topology}'\n"
    )
}

/// The agent installs a new topology by replacement so a concurrent reload never
/// reads a partial setting; the proof has to change it the same way.
fn install_topology(path: &Path, topology: &str) {
    let staging = path.with_extension("staging");
    fs::write(&staging, expected_conf(topology)).expect("stage topology");
    fs::set_permissions(&staging, fs::Permissions::from_mode(0o400)).expect("seal topology");
    fs::rename(&staging, path).expect("install topology");
}

fn initialize_pgdata(bin: &Path, data_dir: &Path) {
    let status = Command::new(bin.join("initdb"))
        .arg(format!("--pgdata={}", data_dir.display()))
        .arg("--username=postgres")
        .arg("--auth-local=trust")
        .arg("--auth-host=reject")
        .arg("--encoding=UTF8")
        .arg("--locale=C")
        .stdout(Stdio::null())
        .status()
        .expect("run initdb");
    assert!(status.success(), "initdb failed: {status}");
}

fn spawn_agent(
    bin: &Path,
    root: &Path,
    data_dir: &Path,
    synchronous_conf_file: &Path,
    address: SocketAddr,
) -> AgentGuard {
    let stderr_path = root.join("agent-stderr.log");
    let stderr = OpenOptions::new()
        .create(true)
        .truncate(true)
        .write(true)
        .mode(0o600)
        .open(&stderr_path)
        .expect("create agent stderr capture");
    let child = Command::new(env!("CARGO_BIN_EXE_pgshard-agent"))
        .env_clear()
        .env("PGSHARD_HTTP_BIND", address.to_string())
        .env("PGSHARD_CLUSTER_ID", "cluster-1")
        .env("PGSHARD_SHARD_ID", "0")
        .env("PGSHARD_INSTANCE_ID", "cluster-1-shard-0-0")
        .env("PGSHARD_POSTGRES_MODE", "quarantine")
        .env("PGDATA", data_dir)
        .env("PGSHARD_POSTGRES_BIN", bin.join("postgres"))
        .env("PGSHARD_POSTGRES_SOCKET_DIR", root.join("socket"))
        .env("PGSHARD_POSTGRES_HBA_FILE", root.join("hba/pg_hba.conf"))
        .env(
            "PGSHARD_POSTGRES_SYNCHRONOUS_CONF_FILE",
            synchronous_conf_file,
        )
        .env("PGSHARD_POSTGRES_SMART_SHUTDOWN_MS", "1000")
        .env("PGSHARD_POSTGRES_FAST_SHUTDOWN_MS", "5000")
        .env("PGSHARD_POSTGRES_IMMEDIATE_SHUTDOWN_MS", "1000")
        .stdin(Stdio::null())
        .stdout(Stdio::null())
        .stderr(Stdio::from(stderr))
        .process_group(0)
        .spawn()
        .expect("spawn agent");
    AgentGuard {
        process_group: Some(Pid::from_child(&child)),
        child: Some(child),
        stderr_path,
    }
}

fn wait_for_quarantine(agent: &AgentGuard, address: SocketAddr) {
    let started = Instant::now();
    loop {
        if let Ok(status) = request_status(address)
            && status.contains(r#""postgres_process":"running_quarantined""#)
        {
            return;
        }
        assert!(
            started.elapsed() < READY_TIMEOUT,
            "quarantine startup timed out; agent stderr:\n{}",
            agent.stderr()
        );
        thread::sleep(Duration::from_millis(50));
    }
}

fn wait_for_stderr(agent: &AgentGuard, expected: &str) {
    let started = Instant::now();
    loop {
        let stderr = agent.stderr();
        if stderr.contains(expected) {
            return;
        }
        assert!(
            started.elapsed() < RELOAD_TIMEOUT,
            "PostgreSQL never reported {expected:?}; agent stderr:\n{stderr}"
        );
        thread::sleep(Duration::from_millis(50));
    }
}

fn postmaster_pid(data_dir: &Path) -> i32 {
    fs::read_to_string(data_dir.join("postmaster.pid"))
        .expect("read postmaster.pid")
        .lines()
        .next()
        .expect("postmaster.pid holds a pid")
        .trim()
        .parse()
        .expect("postmaster pid is numeric")
}

fn command_line(pid: i32) -> Vec<String> {
    fs::read_to_string(format!("/proc/{pid}/cmdline"))
        .expect("read postmaster command line")
        .split('\0')
        .filter(|argument| !argument.is_empty())
        .map(str::to_owned)
        .collect()
}

fn reserve_address() -> SocketAddr {
    let listener = TcpListener::bind("127.0.0.1:0").expect("reserve HTTP address");
    let address = listener.local_addr().expect("read HTTP address");
    drop(listener);
    address
}

fn request_status(address: SocketAddr) -> std::io::Result<String> {
    use std::io::Read;

    let mut stream = TcpStream::connect_timeout(&address, Duration::from_millis(100))?;
    stream.set_read_timeout(Some(Duration::from_secs(1)))?;
    stream.write_all(b"GET /status HTTP/1.1\r\nHost: localhost\r\nConnection: close\r\n\r\n")?;
    let mut response = String::new();
    stream.read_to_string(&mut response)?;
    Ok(response)
}
